baseurl: "/gsetri" # the subpath of your site, e.g. /blog/
image_location: assets/img
javascript_location: assets/js
url: "http://gsetri.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: ['thumbnail.png', 'README.md']
include: ['assets', 'page']

sass:
  sass_dir: assets/_sass
  style: :compressed